import Link from "next/link";
import { ArrowRight, BarChart3, CheckCircle2, ClipboardList, Clock3, Menu, MessageCircle, ShieldCheck, Sparkles, Users, Workflow } from "lucide-react";
import { apiGet } from "@/lib/api-server";
import { CaixaBrand } from "@/components/CaixaBrand";

export const metadata = { title: "CAIXA CRM — organize oportunidades e conquiste resultados", description: "CRM imobiliário para leads, clientes, imóveis, propostas e financiamento em um só lugar.", alternates: { canonical: "/" }, openGraph: { title: "CAIXA CRM — organize oportunidades e conquiste resultados", description: "Um CRM completo para transformar oportunidades em resultados.", type: "website", url: "/", siteName: "CAIXA CRM", locale: "pt_BR" } };

const features = [
  { icon: Users, title: "Gestão de Leads", text: "Organize e acompanhe todas as oportunidades." },
  { icon: Workflow, title: "Funil de Vendas", text: "Visualize cada etapa do seu processo comercial." },
  { icon: Sparkles, title: "Automação", text: "Economize tempo com tarefas automáticas." },
  { icon: ClipboardList, title: "Agenda Integrada", text: "Nunca mais perca um compromisso." },
  { icon: BarChart3, title: "Relatórios Inteligentes", text: "Tome decisões baseadas em dados reais." },
  { icon: Users, title: "Trabalho em Equipe", text: "Mais colaboração e produtividade no dia a dia." },
];
const plans = [
  { name: "Starter", detail: "Ideal para começar", price: "R$ 49", features: ["Até 2 usuários", "Leads ilimitados", "Funil de vendas", "Suporte por e-mail"] },
  { name: "Profissional", detail: "Para equipes em crescimento", price: "R$ 99", featured: true, features: ["Até 10 usuários", "Automações", "Relatórios avançados", "Integrações", "Suporte prioritário"] },
  { name: "Business", detail: "Para grandes operações", price: "R$ 199", features: ["Usuários ilimitados", "Permissões personalizadas", "API e integrações avançadas", "Suporte dedicado"] },
  { name: "Enterprise", detail: "Soluções sob medida", price: "Fale conosco", features: ["Tudo do Business", "Customizações", "SLA diferenciado", "Consultoria especializada"] },
];

function DashboardMockup({ totalClientes = 1248, totalLeads = 320 }) {
  return <div className="marketing-dashboard-mockup" aria-label="Prévia do dashboard CAIXA CRM"><div className="marketing-mockup-sidebar"><CaixaBrand subtitle /><span className="active">⌂ Dashboard</span><span>♙ Leads</span><span>♧ Clientes</span><span>▣ Imóveis</span><span>▤ Propostas</span><span>◈ Relatórios</span><span>⚙ Configurações</span></div><div className="marketing-mockup-main"><div className="marketing-mockup-top"><span>⌕&nbsp; Buscar...</span><small>Flávio M.<br />Administrador</small></div><h3>Olá! <span>👋</span></h3><p>Aqui estão os principais dados do seu negócio.</p><div className="marketing-mockup-kpis"><div><Users /><b>{totalClientes.toLocaleString("pt-BR")}</b><small>Leads</small><em>↑ 12%</em></div><div><Workflow /><b>{totalLeads}</b><small>Oportunidades</small><em>↑ 8%</em></div><div><CheckCircle2 /><b>118</b><small>Negócios fechados</small><em>↑ 23%</em></div></div><div className="marketing-mockup-graphs"><div><strong>Evolução</strong><div className="marketing-mini-chart"><i /><i /><i /><i /><i /><i /></div></div><div><strong>Funil de vendas</strong><div className="marketing-funnel"><i /><i /><i /><i /></div></div></div></div></div>;
}

export default async function LandingPage() {
  const publicData = await apiGet("/public/imoveis?limit=1");
  const totalClientes = publicData?.total ?? 1248;
  return <div className="marketing-page"><header className="marketing-header"><Link href="/" className="marketing-logo"><CaixaBrand /><span>CRM</span></Link><nav><a href="#recursos">Recursos</a><a href="#beneficios">Benefícios</a><Link href="/precos">Planos</Link><a href="#depoimentos">Depoimentos</a><a href="#faq">FAQ</a></nav><div className="marketing-header-actions"><Link href="/login" className="marketing-login-link">Entrar</Link><Link href="/registro" className="marketing-primary small">Começar agora</Link></div><button className="marketing-mobile-menu" aria-label="Abrir menu"><Menu size={22} /></button></header><main>
    <section className="marketing-hero"><div className="marketing-hero-copy"><p className="marketing-eyebrow">ORGANIZE · CONQUISTE · CRESÇA</p><h1>O CRM que transforma oportunidades em <span>resultados.</span></h1><p className="marketing-hero-text">Mais organização, mais produtividade e mais vendas para o seu negócio.</p><div className="marketing-actions"><Link href="/registro" className="marketing-primary">Testar grátis <ArrowRight size={18} /></Link><Link href="/dashboard" className="marketing-secondary">Ver demonstração <span>▷</span></Link></div><div className="marketing-proof"><span><Clock3 size={14} /> Implementação rápida</span><span><MessageCircle size={14} /> Suporte especializado</span><span><ShieldCheck size={14} /> Seguro e confiável</span></div></div><div className="marketing-hero-visual"><DashboardMockup totalClientes={totalClientes} totalLeads={320} /><div className="marketing-visual-swoosh" /></div></section>
    <section className="marketing-trust"><p>EMPRESAS QUE CONFIAM</p><div><strong>CAIXA</strong><strong>VISA</strong><strong>Microsoft</strong><strong>Google</strong><strong>AWS</strong><strong>DELL</strong><strong>Adobe</strong></div></section>
    <section id="recursos" className="marketing-section"><div className="marketing-section-heading"><p className="marketing-eyebrow">RECURSOS COMPLETOS</p><h2>Tudo o que você precisa<br />em um só lugar.</h2><p>Um CRM completo, intuitivo e poderoso para levar a sua gestão para o próximo nível.</p><Link href="/precos" className="marketing-outline">Conheça todos os recursos <ArrowRight size={16} /></Link></div><div className="marketing-feature-grid">{features.map(({ icon: Icon, title, text }) => <article key={title}><span><Icon size={22} /></span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></section>
    <section id="beneficios" className="marketing-device-section"><div className="marketing-device-mockup"><div className="marketing-device-screen"><DashboardMockup totalClientes={358} totalLeads={142} /></div><div className="marketing-phone"><div className="marketing-phone-screen">CAIXA CRM<br /><small>Leads recentes</small><i /><i /><i /></div></div></div><div><p className="marketing-eyebrow">ACESSO EM QUALQUER LUGAR</p><h2>Seu negócio na palma da sua mão.</h2><p>Acesse de onde estiver, pelo computador ou celular. Mais liberdade para você e sua equipe.</p><ul><li><CheckCircle2 /> Interface moderna e intuitiva</li><li><CheckCircle2 /> 100% online e seguro</li><li><CheckCircle2 /> Funciona em qualquer dispositivo</li><li><CheckCircle2 /> Atualizações constantes</li></ul><div className="marketing-store-buttons"><span>▶ Google Play</span><span> App Store</span></div></div></section>
    <section className="marketing-stats-band"><div><p className="marketing-eyebrow">ACESSO EM QUAISQUER</p><h2>Mais controle.<br />Mais produtividade.<br />Mais crescimento.</h2><p>Empresas de todos os tamanhos já estão evoluindo com o CAIXA CRM.<br />Chegou a sua vez.</p></div><div className="marketing-stat-grid"><strong>+40%<small>em produtividade</small></strong><strong>-70%<small>em tarefas manuais</small></strong><strong>+3x<small>mais conversões</small></strong><strong>100%<small>em nuvem e seguro</small></strong></div></section>
    <section id="planos" className="marketing-plans"><p className="marketing-eyebrow">PLANOS PARA CADA MOMENTO</p><h2>Escolha o plano ideal para o seu negócio.</h2><p>Comece hoje mesmo e experimente todo o potencial do CAIXA CRM.</p><div className="marketing-plans-grid">{plans.map((plan) => <article className={plan.featured ? "featured" : ""} key={plan.name}>{plan.featured && <b className="marketing-plan-badge">Mais escolhido</b>}<h3>{plan.name}</h3><small>{plan.detail}</small><strong>{plan.price}{plan.price.startsWith("R$") && <em>/mês</em>}</strong><ul>{plan.features.map((item) => <li key={item}><CheckCircle2 /> {item}</li>)}</ul><Link href="/registro" className={plan.featured ? "marketing-primary" : "marketing-outline"}>{plan.price.startsWith("Fale") ? "Entrar em contato" : "Começar agora"}</Link></article>)}</div></section>
    <section id="depoimentos" className="marketing-testimonials"><p className="marketing-eyebrow">O QUE NOSSOS CLIENTES DIZEM</p><h2>Histórias reais, resultados reais.</h2><div><blockquote>“O CAIXA CRM trouxe mais organização e clareza para o nosso processo. Nossa equipe hoje rende mais e com menos esforço.”<cite>Mariana Costa <small>Diretora Comercial</small></cite></blockquote><blockquote>“Simples de usar, completo e com um suporte incrível. Recomendo para qualquer empresa que quer crescer.”<cite>Ricardo Mendes <small>CEO</small></cite></blockquote><blockquote>“Conseguimos centralizar tudo em um só lugar e agora temos total visibilidade do nosso funil de vendas.”<cite>Juliana Alves <small>Gerente de Operações</small></cite></blockquote></div></section>
    <section id="faq" className="marketing-faq"><p className="marketing-eyebrow">DÚVIDAS FREQUENTES</p><h2>Comece com clareza.</h2><details open><summary>Preciso instalar alguma coisa?</summary><p>Não. O CAIXA CRM funciona online e pode ser acessado pelo computador ou celular.</p></details><details><summary>Posso testar antes de contratar?</summary><p>Sim. O cadastro começa com um período de teste para você conhecer os recursos.</p></details><details><summary>Meus dados ficam protegidos?</summary><p>Sim. A plataforma usa sessão segura e controles de acesso por perfil.</p></details></section>
    <section className="marketing-final-cta"><div><p className="marketing-eyebrow">PRONTO PARA EVOLUIR?</p><h2>Dê o próximo passo com o CAIXA CRM.</h2><p>Teste grátis por 14 dias. Sem cartão de crédito. Sem complicação.</p></div><Link href="/registro" className="marketing-white-button">Começar agora <ArrowRight size={18} /></Link></section>
  </main><footer className="marketing-footer"><div><Link href="/" className="marketing-logo"><CaixaBrand /><span>CRM</span></Link><p>Tecnologia que aproxima pessoas e resultados.</p></div><div><b>Produto</b><Link href="#recursos">Recursos</Link><Link href="/precos">Planos</Link><Link href="/dashboard">Integrações</Link></div><div><b>Empresa</b><Link href="#beneficios">Sobre</Link><Link href="#depoimentos">Depoimentos</Link><Link href="/login">Acesso</Link></div><div><b>Suporte</b><Link href="#faq">Central de ajuda</Link><Link href="/login">Status do sistema</Link></div><div><b>Siga-nos</b><span>in&nbsp;&nbsp;◎&nbsp;&nbsp;▶</span></div><small>© {new Date().getFullYear()} CAIXA CRM. Todos os direitos reservados.</small></footer></div>;
}
